name: PyPI

on:
  push:
    tags:
      - v*

permissions: read-all

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-slim
    environment:
      name: pypi
      url: https://pypi.org/project/ragged-stubs
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
      - run: uv build
      - uses: astral-sh/attest-action@f589a42a7efb6fe400b4f400de60b4bc90390027 # v0.0.6
      - run: uv publish --trusted-publishing always
